### ISSUE TITLE
Animsition support for IE

### ISSUE THREAD

**Issue by shnibble** [shnibble/OvhaiWebsite#12]
IE plays wildly different animations when transitioning through pages using the Animsition scripts.

**Comment by shnibble** [comment]
Looks like IE only uses some animations properly. Can't find anything online about this particular issue. May need to use a different animation plugin for the sake of comparability.

**Comment by Meopicad** [comment]
What the hell is IE?

**Comment by shnibble** [comment]
Internet Explorer
