### ISSUE TITLE
Add Instruments Slideshow

### ISSUE THREAD

**Issue by shnibble** [shnibble/OvhaiWebsite#15]
Add a new panel to home.html for a slideshow with instrument images and descriptions.

**Comment by shnibble** [comment]
Where is this going now, home or media page?

**Comment by Meopicad** [comment]
This will be on the home or about page. Media is only used for the blog tool and social media links. I think some sort of scrolling window will be the best way to do it.

**Comment by shnibble** [comment]
I vote for it going on the about page. I think we talked about that before, yes?

**Comment by Meopicad** [comment]
Yes we did. Put it on About. So what the hell goes on the home page? I guess the logo and a text paragraph. Maybe "text2" located at <about page content/about.txt>

**Comment by shnibble** [comment]
Well the home page usually acts as a guide for the rest of the site. It should have the most important information that a user would be going there to see in the first place, or at least an alert/direction for where to find that info.
