### ISSUE TITLE
Update album-tracks player

### ISSUE THREAD

**Issue by shnibble** [shnibble/OvhaiWebsite#16]
Replace the controller version with a simple play and pause button that fits with the theme better.

**Comment by shnibble** [comment]
Need rune-like versions of a play and pause button designed. Do two versions of each, one large enough for touch input on mobile and another smaller version for desktop.

**Comment by Meopicad** [comment]
Mark and I went over the site and layout last night, he suggested we use soundcloud for playback of our tracks. I will create an account upload the tracks and send you the link when its done.

**Comment by shnibble** [comment]
Okay, sounds good. We'll hold off on this issue until we know how sound cloud can integrate. They may provide code for an in-browser player or just a link.

**Comment by Meopicad** [comment]
Yes it will integrate very easily from what I understand- its pretty much industry standard. This will also resolve the protection and download capability of the tracks as soundcloud provides that service.

**Comment by Meopicad** [comment]
Soundcloud profile is created:  
ovhai.music@gmail.com 
password: CarlSagan3

Harmonic Rain is uploaded, however the track is selected to be private (until we protect and release everything)

Click the "share" button, select embed and there are several options with the code included. The visual one is pretty cool but it may be too large. I will upload the rest once I am back in the states with better wifi. Also I can keep the description out and we can leave it on the site itself, I really like the scrolling effect you have setup.
