### ISSUE TITLE
New banner version without paragraph text

### ISSUE THREAD

**Issue by shnibble** [shnibble/OvhaiWebsite#18]
We need to remove the paragraph text from the banner image and use code to write the text instead. This is so that it does not get cut off on the ends when shrinking the screen as seen here:

![image](https://cloud.githubusercontent.com/assets/7944851/9428182/9ef568d0-4970-11e5-9f82-b9773ca1cfdc.png)

The "Ovhai" text can stay as it fits nicely even on the smallest screen size.

**Comment by Meopicad** [comment]
Will you be able to use a non-standard font if I send it to you?

**Comment by shnibble** [comment]
I will work on it, send it over

**Comment by shnibble** [comment]
Reopening and assigning to myself until the new image is implemented.

**Comment by shnibble** [comment]
Finished this with latest commit.
