### ISSUE TITLE
Create "Media" tab and content

### ISSUE THREAD

**Issue by Meopicad** [shnibble/OvhaiWebsite#19]
After talking with Mark, instead of cramming news articles and blogging content onto the home page, we will create a Media page that will contain an all in one concept. We need to research a blogging tool that we can post content to on the Media page and it will automatically update the same content to Facebook, Twitter, etc.

**Comment by shnibble** [comment]
Good idea. Not really sure where to start but I'll do some google'ing for some sort of plug-in we might be able to adapt for this.
