### ISSUE TITLE
New navigation button images

### ISSUE THREAD

**Issue by shnibble** [shnibble/OvhaiWebsite#20]
The runes by themselves are a good size for the "css/narrow.css" version but we need new versions of the images for "css/style.css" and "css/desktop.css" versions.

<b>css/style.css</b>
Standard buttons with the white text and shadow runes should be 50px high with no extra space surrounding them (i.e. crop the images to their smallest sizes). To replace, edit "css/style.css" lines 119 through 141, updating the "background", "height", and "width" properties so each fits the image size.

<b>css/desktop.css</b>
Desktop buttons with the white text and shadow runes should be 30px high (same as above, crop out extra space). To replace, edit "css/desktop.css" lines 31 through 53.

**Comment by Meopicad** [comment]
Ok. I do not think having the runes by themselves is going to work, as we said before no one will know what button is what. I will play around with a rune button design that is more legible. When I open the site on my phone, it is loading the middle-sized version, not the narrow one.

**Comment by shnibble** [comment]
Newer phones will most likely load the default style so that is normal. The narrow version is for very small resolution devices.

**Comment by Meopicad** [comment]
Where should I put all of these new files? Images folder or should we create a new one just for buttons?

**Comment by shnibble** [comment]
You can keep them in images for now.

**Comment by shnibble** [comment]
Reopening until "narrow.css" versions are implemented. Just pushed an update with the updates for standard and desktop, they look great!

**Comment by shnibble** [comment]
So I changed the narrow mobile version to just use the RUNEnglish text in lieu of any images. I think it looks pretty good, but I'll defer to you if you still want to design smaller rune-ish images instead.

If you like the current style then just close this issue. Otherwise, reassign to me once the new images are added.

**Comment by Meopicad** [comment]
I will work on a design for the narrow version

**Comment by Meopicad** [comment]
Can you just use the larger buttons for the narrow version?

**Comment by shnibble** [comment]
It looks pretty awful, they all stack up and take up almost all of the viewable area on a small screen.

I could do a drop down menu instead, how about that?

**Comment by Meopicad** [comment]
Ok try that
