### ISSUE TITLE
Design Expandable/ Larger Album Artwork

### ISSUE THREAD

**Issue by Meopicad** [shnibble/OvhaiWebsite#33]
The cover art on the albums page is too small, it should really be featured on this page. Either it should expand when you scroll over or click on it, or we redesign the player layout and have it displayed much larger. I can play around in photoshop with the design. Thoughts?

**Comment by shnibble** [comment]
Just upped it to 260px, how big are you thinking for the thumbnail? 

I could make the picture a link to the original which would open it in its raw resolution. I don't think a hovering over effect would be good as it wouldn't work for mobile.
